### ISSUE TITLE
Question about converting to GPL in another project

### ISSUE THREAD

**Issue by ghost** [Matheus28/ws28#19]
I have converted your program from the MIT to the GPLv3, could you help me check if there (notices) are any mistakes.

https://github.com/monokotech/EasyRPG-Multiplayer-Native/blob/dev/src/multiplayer/websocket.cpp

This is what I have referred to:
https://opensource.stackexchange.com/questions/5832/relicensing-an-mit-licensed-project-under-the-gpl-that-has-non-code-contribution/5833#5833

---

Thank you for your contribution, this is the only useful one among many similar projects I have searched for.

**Comment by Matheus28** [comment]
Sorry but I won’t be able to assist you in reviewing the code.
