### ISSUE TITLE
Please reply to this

### ISSUE THREAD

**Issue by bytezeroseven** [Matheus28/ws28#4]
I know this is not the right place to ask this, but I couldn't find any other way to contact you. I tried messaging you on your reddit u/Zeach, but it didn't help. I want to know from where did you learn coding and multiplayer game dev. I have been trying to learn io game dev from an year now. I am still in school and have no other source except the internet for learning. I have shown not many improvements. I often get demotivated and leave the project.

**Comment by Matheus28** [comment]
There are plenty of resources on the internet, this isn't the place for it.

**Comment by bytezeroseven** [comment]
'Please reply to this'?
Where did you learn game dev?

**Comment by BlueCannonBall** [comment]
> Where did you learn game dev?

Start by learning to code.

**Comment by Steve-Dusty** [comment]
You can start here. https://codecombat.com/live-classes
