### ISSUE TITLE
Freezing and disconnecting

### ISSUE THREAD

**Issue by supahero1** [Matheus28/ws28#5]
Soo good job on fixing server crasher and a couple of other things yet, but there is still that one thing that is holding on and was there for a long time, just sometimes not so much... active? Whatever.
The point is random freezing of diep.io, and no, it's not only me. My friends experience that as well. FPS is completely fine, just that either diep.io client or server aren't sending or receiving info. Since I don't know which and you develop each of them, here I am.
I don't remember any errors on client side in console, but anyway if you will respond and ask for seeing the console, I can do it. Game is freezing at random points in time, for random length of time (basically a couple of seconds) and often disconnecting after longer freeze. I hope you will be able to debug and fix this issue.

**Comment by Matheus28** [comment]
This isn't related to this repository.
