### ISSUE TITLE
Great minimalistic ws server code 

### ISSUE THREAD

**Issue by meiry** [Matheus28/ws28#6]
Just to say , i didn't test it but from seeing it looks like minimalistic and right to the point ws server 
i wonder if replacing libuv with plain networking code and memory management will do some difference

**Comment by Matheus28** [comment]
I already use libuv for several other things so eliminating it as a dependency isn't something I desire. Adding cross platform support for networking would add a lot of code.

**Comment by meiry** [comment]
yeah it's great lib ( power nodejs) .
and your games are great! 
do you also use it if you do mobile games ?

**Comment by Koleotank** [comment]
I assume not, but I'm not Matheus
